// Code generated by cmd/iconsgen from @iconify-json/material-symbols 1.2.93 and icons.txt; DO NOT EDIT.

package html

import "github.com/neuroplastio/hotty-a2ui/icons"

// The Material Symbols icons.txt names, Sharp, filled, for HottyIcon
// (icons.Register). Material Symbols are Google's, under the Apache
// License 2.0 (icons/COPYING).
func init() {
	for name, d := range map[string]string{
		// keyboard-arrow-down-sharp
		"keyboard_arrow_down": "m12 15.4l-6-6L7.4 8l4.6 4.6L16.6 8L18 9.4z",
		// keyboard-arrow-up-sharp
		"keyboard_arrow_up": "m12 10.8l-4.6 4.6L6 14l6-6l6 6l-1.4 1.4z",
	} {
		icons.Register(name, icons.Icon{Box: 24, Path: d})
	}
}
