// Command iconsgen writes icons/basic.go: the basic catalog's 59 icon
// names as Material Symbols, Sharp, filled (gov R-4), from Iconify's data
// at the version icons/REV pins. It checks the package against the
// integrity REV records, and fails on any icon that isn't one path on a
// 24 grid, so that basic.go holds nothing the kit can't draw as it is.
//
// Run it from the repository root: make icons. make icons VERSION=…
// pins another version of the package first.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha512"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"regexp"
	"slices"
	"strings"
	"time"
	"unicode"

	"github.com/neuroplastio/hotty-a2ui/icons"
)

const (
	pkg      = "@iconify-json/material-symbols"
	registry = "https://registry.npmjs.org/"
	revFile  = "icons/REV"
	outFile  = "icons/basic.go"
	catalog  = "third_party/a2ui/catalogs/basic/v1/catalog.json"
)

func main() {
	version := flag.String("version", "", "pin this version of "+pkg+" in "+revFile+" first")
	flag.Parse()
	if err := run(*version); err != nil {
		fmt.Fprintln(os.Stderr, "iconsgen:", err)
		os.Exit(1)
	}
}

var client = &http.Client{Timeout: 2 * time.Minute}

func run(version string) error {
	if version != "" {
		if err := pin(version); err != nil {
			return err
		}
	}
	b, err := os.ReadFile(revFile)
	if err != nil {
		return err
	}
	rev := strings.TrimSpace(string(b))
	f := strings.Fields(rev)
	if len(f) != 3 || f[0] != pkg {
		return fmt.Errorf("%s: want %q, a version and an integrity", revFile, pkg)
	}
	tgz, err := get(tarball(f[1]))
	if err != nil {
		return err
	}
	if sum := sha512.Sum512(tgz); "sha512-"+base64.StdEncoding.EncodeToString(sum[:]) != f[2] {
		return fmt.Errorf("%s %s isn't the package %s pins", pkg, f[1], revFile)
	}
	set, err := iconsJSON(tgz)
	if err != nil {
		return err
	}
	names, err := basicNames()
	if err != nil {
		return err
	}
	var src bytes.Buffer
	fmt.Fprintf(&src, `// Code generated by cmd/iconsgen from %s %s; DO NOT EDIT.

package icons

// rev is the %s these shapes were made from.
const rev = %q

// basic are the basic catalog's icon names' shapes: Material Symbols,
// Sharp, filled, with favoriteOff and starOff the unfilled shapes of
// favorite and star (gov R-4). Each has its Iconify name above it.
// Material Symbols are Google's, under the Apache License 2.0 (COPYING).
var basic = map[string]string{
`, pkg, f[1], revFile, rev)
	for _, n := range names {
		key := iconifyName(n)
		d, err := set.path(key)
		if err != nil {
			return fmt.Errorf("%s (%s): %w", n, key, err)
		}
		if _, ok := icons.Path(d); !ok {
			return fmt.Errorf("%s (%s): not path data the kit accepts", n, key)
		}
		fmt.Fprintf(&src, "// %s\n%q: %q,\n", key, n, d)
	}
	src.WriteString("}\n")
	out, err := format.Source(src.Bytes())
	if err != nil {
		return err
	}
	if err := os.WriteFile(outFile, out, 0o644); err != nil {
		return err
	}
	fmt.Printf("%s: %d icons from %s %s, %d bytes of paths\n", outFile, len(names), pkg, f[1], set.bytes)
	return nil
}

// pin writes version, and the integrity the registry has for it, to REV.
func pin(version string) error {
	b, err := get(registry + pkg + "/" + version)
	if err != nil {
		return err
	}
	var meta struct {
		Dist struct{ Integrity string } `json:"dist"`
	}
	if err := json.Unmarshal(b, &meta); err != nil {
		return err
	}
	if !strings.HasPrefix(meta.Dist.Integrity, "sha512-") {
		return fmt.Errorf("%s %s: no sha512 integrity", pkg, version)
	}
	return os.WriteFile(revFile, []byte(pkg+" "+version+" "+meta.Dist.Integrity+"\n"), 0o644)
}

func tarball(version string) string {
	return registry + pkg + "/-/" + pkg[strings.Index(pkg, "/")+1:] + "-" + version + ".tgz"
}

func get(url string) ([]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 64<<20))
}

// iconSet is an Iconify icon set (iconify.design's IconifyJSON).
type iconSet struct {
	Width   int                        `json:"width"`
	Height  int                        `json:"height"`
	Icons   map[string]json.RawMessage `json:"icons"`
	Aliases map[string]json.RawMessage `json:"aliases"`
	bytes   int
}

func iconsJSON(tgz []byte) (*iconSet, error) {
	zr, err := gzip.NewReader(bytes.NewReader(tgz))
	if err != nil {
		return nil, err
	}
	tr := tar.NewReader(zr)
	for {
		h, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return nil, errors.New("the package has no icons.json")
		}
		if err != nil {
			return nil, err
		}
		if h.Name != "package/icons.json" {
			continue
		}
		var s iconSet
		if err := json.NewDecoder(tr).Decode(&s); err != nil {
			return nil, err
		}
		if s.Width != 24 || s.Height != 24 {
			return nil, fmt.Errorf("icons.json: a %d×%d grid, not 24", s.Width, s.Height)
		}
		return &s, nil
	}
}

var body = regexp.MustCompile(`^<path fill="currentColor" d="([^"]+)"/>$`)

// path is an icon's path data, through its aliases. An alias may only name
// its parent: a flip or a rotation would need a transform.
func (s *iconSet) path(key string) (string, error) {
	for range 8 {
		if raw, ok := s.Icons[key]; ok {
			var ic map[string]any
			if err := json.Unmarshal(raw, &ic); err != nil {
				return "", err
			}
			b, _ := ic["body"].(string)
			delete(ic, "body")
			if len(ic) > 0 {
				return "", fmt.Errorf("%s has more than a body: %v", key, ic)
			}
			m := body.FindStringSubmatch(b)
			if m == nil {
				return "", fmt.Errorf("%s isn't one path in currentColor: %.80s", key, b)
			}
			s.bytes += len(m[1])
			return m[1], nil
		}
		raw, ok := s.Aliases[key]
		if !ok {
			return "", errors.New("not in the set")
		}
		var a map[string]any
		if err := json.Unmarshal(raw, &a); err != nil {
			return "", err
		}
		parent, _ := a["parent"].(string)
		delete(a, "parent")
		if parent == "" || len(a) > 0 {
			return "", fmt.Errorf("alias %s is more than a parent: %v", key, a)
		}
		key = parent
	}
	return "", errors.New("aliases too deep")
}

// basicNames are the icon names in the basic catalog's Icon, as A2UI
// pins it.
func basicNames() ([]string, error) {
	b, err := os.ReadFile(catalog)
	if err != nil {
		return nil, err
	}
	var c struct {
		Components struct {
			Icon struct {
				Properties struct {
					Name struct {
						OneOf []struct {
							Enum []string `json:"enum"`
						} `json:"oneOf"`
					} `json:"name"`
				} `json:"properties"`
			} `json:"Icon"`
		} `json:"components"`
	}
	if err := json.Unmarshal(b, &c); err != nil {
		return nil, err
	}
	for _, o := range c.Components.Icon.Properties.Name.OneOf {
		if len(o.Enum) > 0 {
			return slices.Sorted(slices.Values(o.Enum)), nil
		}
	}
	return nil, errors.New(catalog + ": no icon names")
}

// The names A2UI's reference renderers don't get by snake_case alone
// (a2ui web_core Icon.ts): two Material Icons names, and favoriteOff and
// starOff, which Material Icons calls favorite_border and star_border, the
// unfilled shapes of favorite and star.
var (
	renamed  = map[string]string{"play": "play_arrow", "rewind": "fast_rewind"}
	unfilled = map[string]string{"favoriteOff": "favorite", "starOff": "star"}
	// fontNames are names the Material Symbols font gives a glyph besides
	// the one Iconify knows it by: in the Sharp font's codepoints, payment
	// is credit_card's e8a1 and phone is call's f0d4.
	fontNames = map[string]string{"payment": "credit_card", "phone": "call"}
)

// iconifyName is an A2UI icon name's Iconify name in the Sharp style.
// Iconify's names are kebab-case, and a style is a suffix.
func iconifyName(n string) string {
	style := "-sharp"
	if base, ok := unfilled[n]; ok {
		n, style = base, "-outline-sharp"
	}
	if r, ok := renamed[n]; ok {
		n = r
	} else {
		n = snake(n)
	}
	if f, ok := fontNames[n]; ok {
		n = f
	}
	return strings.ReplaceAll(n, "_", "-") + style
}

func snake(s string) string {
	var b strings.Builder
	for _, r := range s {
		if unicode.IsUpper(r) {
			b.WriteByte('_')
			r = unicode.ToLower(r)
		}
		b.WriteRune(r)
	}
	return b.String()
}
